package pojo;
// Generated Oct 13, 2023 12:14:05 PM by Hibernate Tools 4.3.1

import DAOAdmin.DAOLoginAdmin;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;




/**
 * Admin generated by hbm2java
 */
@ManagedBean
public class Admin  implements java.io.Serializable {


     private String username;
     private String password;

    public Admin() {
    }

    public Admin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
public String validasiAdmin() {
        DAOLoginAdmin uDao = new DAOLoginAdmin();
        List<Admin> us = uDao.getBy(username, password);
        try 
        {if (us != null) {
            username = us.get(0).username;
            password = us.get(0).password;
            return "Admin.xhtml";
        }
        
    } catch (Exception e) {
        System.out.println("Error: "+e);
    }
        
        return "GagalLogin";
    }

    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "Admin.xhtml";
    }
}


