package pojo;
// Generated Oct 13, 2023 12:14:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Attendance generated by hbm2java
 */
public class Attendance  implements java.io.Serializable {


     private Integer idAttendance;
     private Classmembership classmembership;
     private Date attendanceDate;
     private String status;

    public Attendance() {
    }

    public Attendance(Classmembership classmembership, Date attendanceDate, String status) {
       this.classmembership = classmembership;
       this.attendanceDate = attendanceDate;
       this.status = status;
    }
   
    public Integer getIdAttendance() {
        return this.idAttendance;
    }
    
    public void setIdAttendance(Integer idAttendance) {
        this.idAttendance = idAttendance;
    }
    public Classmembership getClassmembership() {
        return this.classmembership;
    }
    
    public void setClassmembership(Classmembership classmembership) {
        this.classmembership = classmembership;
    }
    public Date getAttendanceDate() {
        return this.attendanceDate;
    }
    
    public void setAttendanceDate(Date attendanceDate) {
        this.attendanceDate = attendanceDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


