package pojo;
// Generated Oct 13, 2023 12:14:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Classmembership generated by hbm2java
 */
@ManagedBean
public class Classmembership  implements java.io.Serializable {


     private int idClassMembership;
     private Classes classes;
     private Member member;
     private Trainer trainer;
     private String startDate;
     private String endDate;
     private Set attendances = new HashSet(0);

    public Classmembership() {
    }

	
    public Classmembership(int idClassMembership, Classes classes, Member member, Trainer trainer, String startDate, String endDate) {
        this.idClassMembership = idClassMembership;
        this.classes = classes;
        this.member = member;
        this.trainer = trainer;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public Classmembership(int idClassMembership, Classes classes, Member member, Trainer trainer, String startDate, String endDate, Set attendances) {
       this.idClassMembership = idClassMembership;
       this.classes = classes;
       this.member = member;
       this.trainer = trainer;
       this.startDate = startDate;
       this.endDate = endDate;
       this.attendances = attendances;
    }
   
    public int getIdClassMembership() {
        return this.idClassMembership;
    }
    
    public void setIdClassMembership(int idClassMembership) {
        this.idClassMembership = idClassMembership;
    }
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Trainer getTrainer() {
        return this.trainer;
    }
    
    public void setTrainer(Trainer trainer) {
        this.trainer = trainer;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }




}


