package pojo;
// Generated Oct 7, 2023 2:21:55 AM by Hibernate Tools 4.3.1

import DAOExer.DAOTampilExer;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import util.NewHibernateUtil;

/**
 * Exercise generated by hbm2java
 */
@ManagedBean
public class Exercise implements java.io.Serializable {

    private Integer idExcercise;

    @Override
    public String toString() {
        return "Exercise{" + "idExcercise=" + idExcercise + ", excerciseName=" + excerciseName + ", description="
                + description + '}';
    }

    private String excerciseName;
    private String description;
    private Set classeses = new HashSet(0);

    public Exercise() {
    }

    public Exercise(String excerciseName, String description) {
        this.excerciseName = excerciseName;
        this.description = description;
    }

    public Exercise(String excerciseName, String description, Set classeses) {
        this.excerciseName = excerciseName;
        this.description = description;
        this.classeses = classeses;
    }

    public Integer getIdExcercise() {
        return this.idExcercise;
    }

    public void setIdExcercise(Integer idExcercise) {
        this.idExcercise = idExcercise;
    }

    public String getExcerciseName() {
        return this.excerciseName;
    }

    public void setExcerciseName(String excerciseName) {
        this.excerciseName = excerciseName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getClasseses() {
        return this.classeses;
    }

    public void setClasseses(Set classeses) {
        this.classeses = classeses;
    }

    public List<Exercise> tabelexer() {
        DAOTampilExer tdao = new DAOTampilExer();
        // System.out.println("hello world");
        List<Exercise> kar = tdao.ambilexer();
        // System.out.println(kar);
        return kar;
    }

}
