package pojo;
// Generated Oct 6, 2023 10:26:26 PM by Hibernate Tools 4.3.1


import DAOMember.DAOAddMember;
import DAOMember.DAOLoginMember;
import DAOMember.DAOTampilMember;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Member generated by hbm2java
 */
@ManagedBean
public class Member  implements java.io.Serializable {


     private Integer idMember;
     private String memberName;
     private String email;
     private String password;
     private String phone;
     private String address;
     private String dateBirth;

    public String getDateBirth() {
        return dateBirth;
    }

    public void setDateBirth(String dateBirth) {
        this.dateBirth = dateBirth;
    }

    @Override
    public String toString() {
        return "Member{" + "idMember=" + idMember + ", memberName=" + memberName + ", email=" + email + ", password=" + password + ", phone=" + phone + ", address=" + address + ", dateBirth=" + dateBirth + '}';
    }
     private Set classmemberships = new HashSet(0);




    public Member() {
    }

	
    public Member(String memberName, String email, String password, String phone, String address, String dateBirth) {
        this.memberName = memberName;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.address = address;
        this.dateBirth = dateBirth;
    }
    public Member(String memberName, String email, String password, String phone, String address, String dateBirth, Set classmemberships) {
       this.memberName = memberName;
       this.email = email;
       this.password = password;
       this.phone = phone;
       this.address = address;
       this.dateBirth = dateBirth;
       this.classmemberships = classmemberships;
    }
   
    public Integer getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(Integer idMember) {
        this.idMember = idMember;
    }
    public String getMemberName() {
        return this.memberName;
    }
    
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }
    
        public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    public Set getClassmemberships() {
        return this.classmemberships;
    }
    
    public void setClassmemberships(Set classmemberships) {
        this.classmemberships = classmemberships;
    }

//Proses login member
          public String validasiUser() {
        DAOLoginMember uDao = new DAOLoginMember();
        List<Member> us = uDao.getBy(email, password);
          try 
        { if (us != null) {
            email = us.get(0).email;
            password = us.get(0).password;
            return "index";
        }
        
    } catch (Exception e) {
    }
        return "GagalLogin";
    }

public void savedata()
{
    DAOAddMember add = new DAOAddMember();
add.tambah(this);
}

public List<Member> tabelmember()
{
DAOTampilMember tdao=new DAOTampilMember();
    List<Member> kar = tdao.ambilmember();
    System.out.println(kar);
    return kar;
}

    public void delete()
{    
    DAOTampilMember kdao=new DAOTampilMember();
    kdao.hapusmember(idMember);
}
    

        public void update() {
        DAOTampilMember usr = new DAOTampilMember();
        usr.updatemember(this);
     
    }
 
    public String getbyid(int id) {
        DAOTampilMember member = new DAOTampilMember();

        List<Member> member2 = member.getbyId(id);
        if (!member2.isEmpty()) {
            memberName =member2.get(0).memberName;
    email =member2.get(0).email;
    password =member2.get(0).password;
    phone =member2.get(0).phone;
    address =member2.get(0).address;
    dateBirth =member2.get(0).dateBirth;

        }
//        errorU = true;
        return "editMember";
    }
}


