package pojo;
// Generated Oct 13, 2023 12:14:05 PM by Hibernate Tools 4.3.1


import DAOTrainer.DAOAddTrainer;
import DAOTrainer.DAOTampilTrainer;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;

/**
 * Trainer generated by hbm2java
 */
@ManagedBean
public class Trainer  implements java.io.Serializable {


     private Integer idTrainer;
     private String trainerName;
     private String email;
     private String password;
     private int phoneNumber;
     private Set classmemberships = new HashSet(0);

    public Trainer() {
    }

	
    public Trainer(String trainerName, String email, String password, int phoneNumber) {
        this.trainerName = trainerName;
        this.email = email;
        this.password = password;
        this.phoneNumber = phoneNumber;
    }
    public Trainer(String trainerName, String email, String password, int phoneNumber, Set classmemberships) {
       this.trainerName = trainerName;
       this.email = email;
       this.password = password;
       this.phoneNumber = phoneNumber;
       this.classmemberships = classmemberships;
    }
   
    public Integer getIdTrainer() {
        return this.idTrainer;
    }
    
    public void setIdTrainer(Integer idTrainer) {
        this.idTrainer = idTrainer;
    }
    public String getTrainerName() {
        return this.trainerName;
    }
    
    public void setTrainerName(String trainerName) {
        this.trainerName = trainerName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Set getClassmemberships() {
        return this.classmemberships;
    }
    
    public void setClassmemberships(Set classmemberships) {
        this.classmemberships = classmemberships;
    }


public List<Trainer> tabeltrainer()
    {
        DAOTampilTrainer tdao=new DAOTampilTrainer();
        //System.out.println("hello world");
        List<Trainer> kar = tdao.ambiltrainer();
        System.out.println(kar);
        return kar;
    }
    
//  public String editTrainer() {
//        DAOTampilTrainer train = new DAOTampilTrainer();
//        train.updatetrainer(this);
//        trainerName = this.getTrainerName();
//        email = this.getEmail();
//        password = this.getPassword();
//        phoneNumber = this.getPhoneNumber();
//        classmemberships = this.getClassmemberships();
//        
//
//        FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO, "Berhasill Update Data", null);
//        return "HalamanTrainer";
//    }

  
    public void delete()
{    
    DAOTampilTrainer kdao=new DAOTampilTrainer();
    kdao.hapustrainer(idTrainer);
}
  public void savedata()
{
    DAOAddTrainer add = new DAOAddTrainer();
add.tambah(this);

}
     public void update() {
        DAOTampilTrainer usr = new DAOTampilTrainer();
        usr.updatetrainer(this);
     
    }
     public String getbyid(int id) {
        DAOTampilTrainer trainer = new DAOTampilTrainer();

        List<Trainer> trainer1 = trainer.getbyId(id);
        if (!trainer1.isEmpty()) {
            trainerName =trainer1.get(0).trainerName;
    email =trainer1.get(0).email;
    password =trainer1.get(0).password;
    phoneNumber =trainer1.get(0).phoneNumber;
 

        }
//        errorU = true;
        return "editTrainer";
    }
  
}


